language: node_js
node_js:
  - "stable"
addons:
  firefox: "latest"

env:
  global:
    - DISPLAY=:99.0
    - JPM_FIREFOX_BINARY=/usr/local/bin/firefox

Git:
  submodules: false

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive